// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProjectAuthentication.Repo;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniprojectAuthentication.Repo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630025008_remoke_feilds_in_RefreshToken")]
    partial class remoke_feilds_in_RefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Hành động (Ví dụ: CREATE, UPDATE, DELETE)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Mô tả chi tiết hành động");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Tên bảng/thực thể bị tác động (Ví dụ: User, Product)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasComment("Giá trị mới sau khi sửa (thường lưu JSON)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("Giá trị cũ trước khi sửa (thường lưu JSON)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e01b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            Action = "CREATE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Admin tạo danh mục tin tức mới: Công nghệ",
                            Entity = "Category",
                            EntityId = new Guid("11a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            IsDeleted = false,
                            NewValue = "{\"Id\":\"11a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c\",\"Title\":\"Công nghệ\",\"ParentId\":null}",
                            OldValue = "{}",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("f02c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            Action = "UPDATE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 28, 16, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Thay đổi trạng thái xác thực email của người dùng Nguyễn Văn A",
                            Entity = "User",
                            EntityId = new Guid("3f8e2d1c-bc5a-4912-8fcd-987654fedcba"),
                            IsDeleted = false,
                            NewValue = "{\"EmailVerified\":true}",
                            OldValue = "{\"EmailVerified\":false}",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        });
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Title = "Công nghệ",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("22b3c4d5-6e7f-8a9b-0c1d-2e3f4a5b6c7d"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ParentId = new Guid("11a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            Title = "Điện thoại",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("33c4d5e6-7f8a-9b0c-1d2e-3f4a5b6c7d8e"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ParentId = new Guid("11a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            Title = "Laptop",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("44d5e6f7-8a9b-0c1d-2e3f-4a5b6c7d8e9f"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ParentId = new Guid("11a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            Title = "Trí tuệ nhân tạo (AI)",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("55e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Title = "Giải trí & Đời sống",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("66f7a8b9-0c1d-2e3f-4a5b-6c7d8e9f0a1b"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ParentId = new Guid("55e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a"),
                            Title = "Điện ảnh / Phim truyền hình",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("77a8b9c0-1d2e-3f4a-5b6c-7d8e9f0a1b2c"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            ParentId = new Guid("55e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a"),
                            Title = "Du lịch & Khám phá",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        });
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.CategoryNew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NewsId");

                    b.ToTable("CategoryNews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            CategoryId = new Guid("22b3c4d5-6e7f-8a9b-0c1d-2e3f4a5b6c7d"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            NewsId = new Guid("fa112233-4455-6677-8899-aabbccddeeff")
                        },
                        new
                        {
                            Id = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4b3c2d1e"),
                            CategoryId = new Guid("33c4d5e6-7f8a-9b0c-1d2e-3f4a5b6c7d8e"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            NewsId = new Guid("fb223344-5566-7788-99aa-bbccddeeff11")
                        });
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.New", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa112233-4455-6677-8899-aabbccddeeff"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bài viết phân tích sâu về hiệu năng, thời lượng pin và camera của thế hệ iPhone mới nhất năm 2026.",
                            IsDeleted = false,
                            PictureUrl = "https://cdn.example.com/images/iphone17-review.jpg",
                            Status = "Published",
                            Title = "Đánh giá chi tiết iPhone 17 Pro Max sau 1 tuần sử dụng",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef"),
                            ViewCount = 150
                        },
                        new
                        {
                            Id = new Guid("fb223344-5566-7788-99aa-bbccddeeff11"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 27, 14, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tổng hợp danh sách những chiếc laptop gaming mạnh mẽ, tối ưu phân khúc giá từ tầm trung đến cao cấp.",
                            IsDeleted = false,
                            PictureUrl = "https://cdn.example.com/images/top-laptops-2026.jpg",
                            Status = "Published",
                            Title = "Top 5 Laptop Gaming đáng mua nhất nửa đầu năm 2026",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 27, 14, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef"),
                            ViewCount = 89
                        });
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Đã bị thu hồi/vô hiệu hóa chưa");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Hash của Refresh Token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c01a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 28, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExpiredAt = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Revoked = false,
                            TokenHash = "v3_hash_abcdef1234567890_token_string_here",
                            UserId = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef")
                        },
                        new
                        {
                            Id = new Guid("d02b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 10, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExpiredAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Revoked = true,
                            RevokedAt = new DateTime(2026, 6, 10, 15, 30, 0, 0, DateTimeKind.Utc),
                            TokenHash = "v3_hash_9876543210fedcba_old_token_string",
                            UserId = new Guid("3f8e2d1c-bc5a-4912-8fcd-987654fedcba")
                        });
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái khóa tài khoản");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Mật khẩu đã được hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a2b9c1d-ef4a-4b23-a123-456789abcdef"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@identityservice.com",
                            EmailVerified = true,
                            IsDeleted = false,
                            IsLocked = false,
                            PasswordHash = "Hung2006@",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("3f8e2d1c-bc5a-4912-8fcd-987654fedcba"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "nguyenvana@gmail.com",
                            EmailVerified = false,
                            IsDeleted = false,
                            IsLocked = false,
                            PasswordHash = "Hung2006@",
                            PhoneNumberConfirmed = false,
                            Role = "Customer",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.AuditLog", b =>
                {
                    b.HasOne("MiniProjectAuthentication.Repo.Entity.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.Category", b =>
                {
                    b.HasOne("MiniProjectAuthentication.Repo.Entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MiniProjectAuthentication.Repo.Entity.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.CategoryNew", b =>
                {
                    b.HasOne("MiniProjectAuthentication.Repo.Entity.Category", "Category")
                        .WithMany("CategoryNews")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniProjectAuthentication.Repo.Entity.New", "New")
                        .WithMany("CategoryNews")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("New");
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.New", b =>
                {
                    b.HasOne("MiniProjectAuthentication.Repo.Entity.User", "User")
                        .WithMany("News")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.RefreshToken", b =>
                {
                    b.HasOne("MiniProjectAuthentication.Repo.Entity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.Category", b =>
                {
                    b.Navigation("CategoryNews");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.New", b =>
                {
                    b.Navigation("CategoryNews");
                });

            modelBuilder.Entity("MiniProjectAuthentication.Repo.Entity.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Categories");

                    b.Navigation("News");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
